name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  reload_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: remotely pull and reload Flask
        uses: fifsky/ssh-action@master
        env:
          DIR: ${{ secrets.DIR }}
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          command: |
            git -C $DIR pull
            touch $DIR/uwsgi.ini
