name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  reload_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: remotely pull and reload Flask
        uses: appleboy/ssh-action@v1.0.0
        env:
          DIR: ${{ secrets.DIR }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git -C $DIR pull
            touch $DIR/uwsgi.ini
